version: 2.1
executors:
  node-executor:
    docker:
      - image: circleci/node:14

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run:
          name: Run tests
          command: npm test

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
